language: python
addons:
  apt:
    packages:
    - verilator    
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev

install:
# install conda for py 3.7
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
# End install conda
- pip install magma-lang mantle fault
script:
- python tests/test_install.py
